### ISSUE TITLE
python 3.x compatibility

### ISSUE THREAD

**Issue by guiguem** [project8/dripline-python#1]
_From @laroque on July 24, 2015 17:55_

It would be great if we could officially support python 3. Ideally we'll support both or even give up python 2 and just run in 3. Before we can do that there needs to be some pretty extensive testing of all the components. In particular to make sure we're not using list methods on the output of functions that now return generators (eg. the dpph_scan tries to sort(zip(data_list_1, data_list_2)) which fails).

_Copied from original issue: project8/dripline#100_

**Comment by wcpettus** [comment]
Resolved, the code runs in python3.
Any remaining edge cases should be flagged and patched
