### ISSUE TITLE
cleanup scheduler class

### ISSUE THREAD

**Issue by laroque** [project8/dripline-python#17]
The scheduler class was written considering only the case of sensor loggers and the implementation is overly specific to that case. The scheduler should just handle calling a method on some fixed interval in a way that leverages the async timers in pika rather than with a blocking loop:
- keep the `_log_a_value(self)` method but rename it to something more clearly generic and note that it should be overridden in child classes
- rename the "logging_status" and "log_interval" properties to something more clear/generic
- move the sensor-specific implementations into the spime class, since that is specifically for the case of loggers
- in Spime, create properties "logging_status" and "log_interval" that map onto the new names from above so that the existing interface is preserved for loggers

**Comment by wcpettus** [comment]
fixed in v3.5.5 by PR #18
