### ISSUE TITLE
more advanced watchdog

### ISSUE THREAD

**Issue by guiguem** [project8/dripline-python#2]
_From @laroque on June 4, 2015 17:31_

A monitor was created to externally watch for new sensor values to stop showing up, and issue an alert (for now via twitter) when new values stop appearing. This is useful as an external process as if the lab network is down, internal processes can't get a signal out.

It would be nice to expand the alerts sent to users. The main case being acceptable ranges of values for various loggers. (ie send an twitter/email/whatever if the coldhead goes above 60 K, if the bore pressure goes above 1e-3 torr, if the cell goes above 150 K, LHe level is under 20%, whatever you like).

_Copied from original issue: project8/dripline#84_

**Comment by guiguem** [comment]
I think Gray worked on that, but no final version of the service/config file was given. Someone could continue this work, if more documentation is given.

**Comment by wcpettus** [comment]
This is implemented as a feature in dragonfly via the sensor_monitor in release v1.9.0
