### ISSUE TITLE
Add ms in the sender_info timestamp

### ISSUE THREAD

**Issue by guiguem** [project8/dripline-python#20]
Will help reducing the number of entries to be saved in the database rejected because of conflicting timestamps.
Will require a bump in the wp protocol version.

**Comment by wcpettus** [comment]
I have verified that the database already supports timestamp precision down to microseconds.  Once you add a period to the timestamp, python is agnostic whether you go to milli, micro, or nanosecond precision.

**Comment by wcpettus** [comment]
dripline doesn't care, a few dragonfly services require consistency with each other:
- pid_loop must be consistent with the endpoint it is triggering on
- pinger and sensor_monitor must be consistent with the operator silence
- sql_snapshot, daq_db_interface, and daq_run_interface need consistency

updated and nothing crashed
